# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('date_start', models.DateTimeField(verbose_name='Data de Início')),
                ('date_end', models.DateTimeField(verbose_name='Data de Término')),
                ('estimated_public', models.IntegerField(verbose_name='Público Estimado')),
                ('description', models.CharField(max_length=600, verbose_name='Descrição')),
                ('other_informations', models.CharField(max_length=400, verbose_name='Demias Informações')),
                ('name_institute', models.CharField(max_length=200, verbose_name='Local')),
                ('institute_address', models.CharField(max_length=200, verbose_name='Endereço')),
            ],
        ),
    ]
