# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='other_informations',
            field=models.CharField(max_length=400, verbose_name='Demais Informações'),
        ),
    ]
