# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 19:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0003_auto_20170703_1644'),
        ('events', '0002_auto_20170610_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.Event', verbose_name='Evento')),
                ('user', models.ForeignKey(help_text='Usuário responsável pelo evento.', on_delete=django.db.models.deletion.PROTECT, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('video', models.ManyToManyField(related_name='events', to='videos.Video')),
            ],
        ),
    ]
