# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 01:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_voting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='events.Event', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='user',
            field=models.ForeignKey(help_text='Usuário responsável pelo evento.', on_delete=django.db.models.deletion.PROTECT, related_name='votings', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='video',
            field=models.ManyToManyField(related_name='votings', to='videos.Video'),
        ),
    ]
