# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170703_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='already_finished',
            field=models.BooleanField(default=False),
        ),
    ]
