# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_voting_already_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='already_finished',
            new_name='already_closed',
        ),
    ]
