# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170703_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='password',
            field=models.CharField(max_length=400, null=True, verbose_name='Senha'),
        ),
    ]
