# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_name',
            new_name='name',
        ),
    ]
