# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_vote_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='events.Event'),
        ),
    ]
