# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_universidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='universidade',
        ),
    ]
